### ISSUE TITLE
Ways to improve

### ISSUE THREAD

**Issue by stsrki** [araxis/Arax.Blazorise.Server.Templates#1]
Hi, just a few tips to improve the templates and make them better integrated with Blazorise

- https://github.com/araxis/Arax.Blazorise.Server.Templates/blob/master/Bootstrap5App/Pages/FetchData.razor use DataGrid instead of `table` elements
- https://github.com/araxis/Arax.Blazorise.Server.Templates/blob/master/Bootstrap5App/Pages/Counter.razor replace HTML elements with Heading, Paragraph, and Button components
- https://github.com/araxis/Arax.Blazorise.Server.Templates/blob/master/Bootstrap5App/Pages/_Layout.cshtml#L13 site.css should go after blazorise CSS files

**Comment by araxis** [comment]
@stsrki Thank you for your comments.

These changes have been made.

0fc99f5 [site.css moved after blazorise CSS files](https://github.com/araxis/Arax.Blazorise.Server.Templates/commit/0fc99f50b4c31dabbfdbe29a4994c2e8a9e24bbc)

4269d41 [use DataGrid instead of table elements](https://github.com/araxis/Arax.Blazorise.Server.Templates/commit/4269d413e088b922bb27061afab12b61eee04ce8)

3b54d1e [use DataGrid instead of table elements](https://github.com/araxis/Arax.Blazorise.Server.Templates/commit/4269d413e088b922bb27061afab12b61eee04ce8)

**Comment by stsrki** [comment]
Looking good. But I noticed you also downgraded to 1.0.1?

**Comment by araxis** [comment]
Because of these issues [#3656](https://github.com/Megabit/Blazorise/issues/3656) & [#3651](https://github.com/Megabit/Blazorise/issues/3651).
After trying your [solution](https://github.com/Megabit/Blazorise/issues/3651#issuecomment-1083256314), I'll update if it works for all templates.
thanks.

**Comment by stsrki** [comment]
Ah yeah, that is a valid reason. It will be fixed soon.
